name: Build Fairy Ring Hotkeys

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - run: gradle clean build

      - uses: actions/upload-artifact@v4
        with:
          name: fairy-ring-hotkeys-jar
          path: build/libs/*.jar
